### ISSUE TITLE
Feature Cart

### ISSUE THREAD

**Issue by KhanhVanCong** [KhanhVanCong/Book-Store-Rails-7#1]
#### Context: 
Our company is making a campaign to survey the ability to purchase from customers. Thus, we need to build this feature as soon as possible to adapt to it.
#### Logic: 
Each user has only one cart. Users can add/remove books to their cart. Furthermore, they can also empty their cart with one click.
#### Todo:
- [x] Design DB: 
<img width="833" alt="image" src="https://user-images.githubusercontent.com/34101200/225498576-f886a9a3-bf27-4f4c-bbf6-f011a8cd5b17.png">

- [x] Create db migrate base on Design

- [x] Create Class **Cart**:
  - Properties: Id, user_id
  - Relationship: has_many **Orders**, has_many **Books** via **Orders**

- [x] Create Class **Order**:
  - Properties: Id, cart_id, book_id
  - Relationship: belong_to **Cart**, belong_to **Book**
  - Index: [ cart_id, book_id]: unique

- [x] Create Class **Book**:
  - Properties: Id
  - Relationship: has_many **Orders**, has_many **Carts** via **Orders**

- [x] Create Controller "Cart"
  - Functions:
    - Add one book to the cart
        - Logic: 
          - User needs to log in to use this function
          - Find a book via the book's id
          - Find a cart of current_user  
          - Add cart and book to Order
        - Testing:
          - Users can add books to their cart
          - Users can't add books to their cart if they don't log in
          - Users can't add books to the cart which does not belong to their
    - Remove one book from the cart
      - Logic:
        - User needs to log in to use this function
        - Find a book via the book's id
        - Find a cart of current_user 
        - Find the order via the book's id and cart's id
        - Remove this order
      - Testing:
        - Users can remove books from their cart
        - Users can't remove books from other carts
        - Users can't remove books that do not belong to their cart
    - Empty all books in the cart
      - Logic:
        - Find all orders through the cart's id
        - Remove all orders
      - Testing:
        - User can remove all orders
        - User can't remove all orders that do not belong to their cart
    - Show all books in the cart
      - Logic:
        - Find all books in the cart of the current user
        - Calculator the total price of these books
        - Render these books
      - Testing:
        - Users can see all books that they added before
        - Users can see other books that they didn't add
        - Users can see the total price of all books in their cart
#### Reference: 
- https://yonedesign.medium.com/how-i-implemented-a-simple-shopping-cart-in-a-rails-react-app-b4c6cc2b6205
- https://medium.com/@yxp010/simple-shopping-cart-in-rails-ece6f51b27e6
- https://wpbingosite.com/wordpress/bootin/home-2
- Gem: https://github.com/dabit/acts_as_shopping_cart
