### ISSUE TITLE
Feature Payment

### ISSUE THREAD

**Issue by KhanhVanCong** [KhanhVanCong/Book-Store-Rails-7#3]
#### Context: 
After users add items (books) to their cart, they can pay via Visa card, Grab Pay, or PayNow. These methods of payment are widespread in the Singapore market.
#### Logic: 
We will use Stripe (a professional online payment company) to control all transactions. We don't save any customer's account information. Customers can request to cancel the order within 2 hours and get the full amount paid.
#### Todo:
- [ ] Design DB: 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/34101200/229956950-68183723-4e49-4212-81cf-997eedbd0ed1.png">

- [ ] Create db migrate base on the design.

- [ ] Create Class **Order**:
  - Properties: Id, ref_no, user_id, order_book_id, order_date_time, full_price, shipping_address, status, stripe_charge_id, stripe_refund_id, stripe_application_id.
  - Relationship: has_many **Order_Books**, has_many **Books** via **Order_Books**, belong_to **User**.

- [ ] Create Class **OrderBook**:
  - Properties: Id, order_id, book_id, book_name, price_per_unit, quantity.
  - Relationship: belong_to **Order**, belong_to **Book**.
  - Index: [ order_id, book_id]: unique.
 
- [ ] Update Class **Book**:
  - Relationship: has_many **OrderBook**.
 
- [ ] Update Class **User**:
  - Relationship: has_many **UserLocation**, has_many **Order**.

- [ ] Create Class **Location**:
  - Properties: Id, address, user_id.
  - Relationship: belong_to **User**.

- [ ] Create Controller **Order**
  - **Functions**:
    -  Note: Users need to log in to use these functions.
    - **Order Page**
        - Logic: 
          - Show all books and the total price in the current user's cart.
          - Add the user's address.
        - Testing:
          - ....
    - **Payment**
      - Logic:
        - Empty cart.
        - Create an order with the status "Pending".
        - Call Stripe and redirect the user to the Stripe page to make a payment.
        - Using webhook and waiting for the status of this payment from Stripe.
        - Update the status of this order. The status may be "confirmed", "failed", or "completed".
        - Send emails to the user to inform the status of this order.
        - Meaning of statuses:
          - **Pending**: process payment.
          - **Confirmed**: complete payment.
          - **Failed**: failed payment.
          - **Completed**: completed order (complete payment + delivery).
      - Testing:
        - Users can't use this function if they don't log in.
        - Users can create an order and make a successful payment.
        - Check the status of the order in cases: successful payment, failed payment.
    - **Cancel order**
      - Logic:
        - Check the possibility of order cancellation following these conditions. 
          - The Order's status is "Pending": the order can be canceled, if the user does not complete payment, the order's status will be set to "Failed".
          - The Order's status is "Confirmed":  the order can be canceled within 2 hours from the created order.
          - The Order's status is "Completed" or "Failed": can't cancel the order.
        - Refund the full amount paid.
        - Set the status of the order to **Cancelled**
        - Send emails to the user to inform the status of this order
      - Testing:
        - The User can cancel this order within 2 hours.
        - The user can't cancel this order after 2 hours.
        - Check the refund transaction in Stripe.
    - **Reorder**
      - Logic:
        - Get all details of the old order.
        - Create a new order with these details.
      - Testing:
        - Users can reorder.
#### Reference: 
- https://stripe.com/docs/payments/checkout/how-checkout-works
- https://stripe.com/docs/testing
- Gem: https://rubygems.org/gems/stripe
